# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Meyer Lab Web
    url: https://www.meyerlab.com.py/
  - name: Meyer Lab SMTP
    check: "tcp-ping"
    url: vps-1397470-x.dattaweb.com
    port: 465
  - name: Meyer Lab IMAP
    check: "tcp-ping"
    url: vps-1397470-x.dattaweb.com
    port: 993
  - name: Meyer Lab POP
    check: "tcp-ping"
    url: vps-1397470-x.dattaweb.com
    port: 995
  - name: Prueba Web caida
    url: web.caida.com.nz
  #- name: Meyer Lab IMAP
    #url: vps-1397470-x.dattaweb.com:993
  #- name: Meyer Lab POP
   # url: vps-1397470-x.dattaweb.com:995
 

assignees:
  - informaticaMeyerlab

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
